Update Debian packages for qtbridge 0.3
With the introduction of the registry we require the private header
qqmldata_p.h. The first build on docs.rs, for example, failed with

warning: qtbridge-runtime@0.3.0: src/cpp/registry.cpp:8:10:
                fatal error: private/qqmldata_p.h: No such file or directory
warning: qtbridge-runtime@0.3.0:     8 | #include <private/qqmldata_p.h>
warning: qtbridge-runtime@0.3.0:       |          ^~~~~~~~~~~~~~~~~~~~~~
warning: qtbridge-runtime@0.3.0: compilation terminated.

On Ubuntu we require the additional package qt6-declarative-private-dev
which has been proven to be the solution on docs.rs.

Fedora has a package qt6-qtbase-private-devel but it has no package
qt6-qtdeclarative-private-devel as one would assume. However, the
private header private/qqmldata_p.h can be found in the package
qt6-qtdeclarative-devel
(https://packages.fedoraproject.org/pkgs/qt6-qtdeclarative/qt6-qtdeclarative-devel/).
Therefore, nothing changes for Fedora, which was tested in a VM.

Fixes: QTBRIDGES-372
Change-Id: Iefa7d5f5b365cf97cac2ffc49bf10fc6f9ea8c43
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>